Pipeline separation
microsoftgraph/msgraph-sdk-raptor pull request #1018
Opened 2022-05-06 17:09 UTC by timayabi2020

This PR is supposed to address issues
1. https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/1011
2. https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/937
### Changes proposed in this pull request
-  Have known issues for v1 and beta tests run on their own pipelines i.e. One Job will handle only one test type as per the pipeline configuration on the yaml files.
- Recreate powershell visualization chart to separately show metrics for Execution tests and that for Known failure tests. See sample screnshot below.
 
<img width="978" alt="image" src="https://user-images.githubusercontent.com/10947120/167179784-19d04211-a91d-4278-8ea8-9e27603e6346.png">

2022-05-06 22:18 UTC, MIchaelMainer approved these changes

2022-05-06 22:55 UTC, zengin requested changes

2022-05-06 22:55 UTC, zengin commented on azure-pipelines/powershell-templates/prod-beta-powershell-scheduled-execution-tests-weekly-knownissues.yml
> +            projectFileName: PowerShellBetaExecutionKnownFailureTests
I think we don't need a jobs array anymore. We can go straight into `steps` similar to other Raptor pipelines.

2022-05-07 07:47 UTC, timayabi2020 commented on azure-pipelines/powershell-templates/prod-beta-powershell-scheduled-execution-tests-weekly-knownissues.yml
> +            projectFileName: PowerShellBetaExecutionKnownFailureTests
> I think we don't need a jobs array anymore. We can go straight into `steps` similar to other Raptor pipelines.

I have removed them

2022-05-09 15:13 UTC, zengin approved these changes

2022-05-09 18:34 UTC, merged