Move failing tests to backup folder
microsoftgraph/msgraph-sdk-raptor pull request #1089
Opened 2022-06-02 16:00 UTC by fey101

- fixes #

### Changes proposed in this pull request
-
-
-

### Other links
-
-
-

2022-06-06 09:39 UTC, rkodev requested changes

2022-06-06 09:39 UTC, rkodev commented on TestsCommon/GoTestRunner.cs
> +        int maxRetryCounts = 160;
Given that its possible for the number of tests to fluctuate, we could add a dynamic retry ceiling i.e `number of files / 10`

2022-06-06 09:39 UTC, rkodev commented on TestsCommon/GoTestRunner.cs
> +            return resultDict;
minor: optional: reduce code complexity. exit on first failed if and avoid wrapping the second code block in an else

```c#
        if (!errors.Any())
            return resultDict;
        
        foreach (var errorline in errors)
        {
            if (!errorline.Contains("compiles.go")) continue;
            var items = errorline.Split(": ");
            var filename = items[0].Split(":").First().Split("src\\")[1];
            var message = errorline;
            var errorCode = items[1];

            var payload =  (resultDict.ContainsKey(filename)) ? resultDict[filename] :  new Collection<Dictionary<string, string>>();

            payload.Add(
                new Dictionary<string, string> {
                    {"errorCode", errorCode},
                    {"errorMessage", message}
                }
            );

            resultDict[filename] = payload;
        }
        return resultDict;
```

2022-06-06 09:39 UTC, rkodev commented on TestsCommon/GoTestRunner.cs
> +                var filename = items[0].Split(":").First().Split("src\\")[1];
possible bug: directly accessing array index without checking length / size.

2022-06-16 16:08 UTC, zengin commented
closing based on the decision from daily sync

2022-06-16 16:08 UTC, closed without merging