Feat/ts execution tests
microsoftgraph/msgraph-sdk-raptor pull request #1128
Opened 2022-06-27 09:09 UTC by rkodev

Resolves https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/1041

Refactors TS tests to externalize dependencies (should take advantage of dependabot)
Adds execution tests for TS
Removes indirection in the flow of TS tests execution
minor: Improve code execution time, avoid parsing the sources twice

2022-06-27 13:44 UTC, timayabi2020 approved these changes

2022-07-01 18:16 UTC, zengin requested changes

2022-07-01 18:16 UTC, zengin commented on TestsCommon/TypeScriptTestRunner.cs
> +                var fileContent = File.ReadAllText(fullPath);
please use the Async alternative.

2022-07-01 18:16 UTC, zengin commented on TestsCommon/TypeScriptTestRunner.cs
> +                if (errors.Count == 0) break;
nit: run this check right after parsing NPM errors.

2022-07-01 18:16 UTC, zengin commented on TestsCommon/TypeScriptTestRunner.cs
> +                    File.Move(Path.Combine(buildDir, item.Key), Path.Combine(backUpDir, item.Key));
Do we need a separate loop here? Can we make File.Move part of the loop above?

2022-07-01 18:16 UTC, zengin commented on TestsCommon/TypeScriptTestRunner.cs
> +                var fileContent = File.ReadAllText(Path.Combine(backupDirectory, fileName));
```suggestion
                var fileContent = await File.ReadAllTextAsync(Path.Combine(backupDirectory, fileName)).ConfigureAwait(false);
```

2022-07-01 18:16 UTC, zengin commented on TestsCommon/TypeScriptTestRunner.cs
> +                        var errorPositionStart = int.Parse(errorPositionsMatch.Groups[2].Value);
please address the warnings raised in the build process.

2022-07-01 18:16 UTC, zengin commented on TestsCommon/TypeScriptTestRunner.cs
> +                var fileContent = File.ReadAllText(fileLocation);
```suggestion
                var fileContent = await File.ReadAllTextAsync(fileLocation).ConfigureAwait(false);
```

2022-07-01 18:16 UTC, zengin commented on TypeScriptV1Tests/SnippetCompileV1Tests.cs
> +                TestType = TestType.ExecutionStable
I don't think this change is intended.

2022-07-01 18:16 UTC, zengin commented on TestsCommon/MicrosoftGraphTypescriptCompiler.cs
> -﻿using System.Collections.ObjectModel;
Thank you for removing this layer!

2022-07-02 15:31 UTC, rkodev commented on TestsCommon/TypeScriptTestRunner.cs
> +            DirectoryInfo directoryInfo = new DirectoryInfo(Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "TsDependecies"));
Yes the `TsDependencies` are copied over from the project folder `TypeScriptV1Tests` for all the other tests. For example we can know issues project references the dependencies via the project import [here ](https://github.com/microsoftgraph/msgraph-sdk-raptor/blob/feat/ts-execution-tests/TypeScriptV1KnownIssueTests/TypeScriptV1KnownIssueTests.csproj)


```
  <ItemGroup>
    <None Remove="..\TypeScriptV1Tests\TsDependecies\package-lock.json" />
    <None Remove="..\TypeScriptV1Tests\TsDependecies\package.json" />
    <None Remove="..\TypeScriptV1Tests\TsDependecies\tsconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\TypeScriptV1Tests\TsDependecies\package-lock.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\TypeScriptV1Tests\TsDependecies\package.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\TypeScriptV1Tests\TsDependecies\tsconfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

```

2022-07-03 05:19 UTC, zengin approved these changes

2022-07-03 14:59 UTC, merged