Resolve Auth for TypeScript Execution Test
microsoftgraph/msgraph-sdk-raptor pull request #1142
Opened 2022-07-05 16:02 UTC by rkodev

1. Provides an authentication token for the TS Execution Tests
2. Improve error string serialization for execution tests
3. Ignore snippets failing compilation for TS execution

2022-07-06 20:18 UTC, rkodev commented on TestsCommon/TypeScriptTestRunner.cs
> +        private async Task generateRequestInformationFiles(IEnumerable<LanguageTestData> languageTestData)
To extract the http url, needed later to get the scopes available, this section extracts the snippet and transforms it from 

```
const graphServiceClient = msgraph_sdk_javascript_1.GraphServiceClient.init({ authProvider });
const result = async () => {
    await graphServiceClient.identityGovernance.entitlementManagement.accessPackageAssignmentsById("accessPackageAssignment-id").get();
};
result().then(resp => {
    console.log(resp);
});

```

to 

```
const graphServiceClient = msgraph_sdk_javascript_1.GraphServiceClient.init({ authProvider });
const req =  graphServiceClient.identityGovernance.entitlementManagement.accessPackageAssignmentsById("accessPackageAssignment-id").createGetRequestInformation()
const url = req.URL
const method = req.httpMethod;
console.log("url: " + url);
console.log("httpMethod: " + method);

```

2022-07-06 20:21 UTC, rkodev commented on TestsCommon/TypeScriptTestRunner.cs
> +                                        .Replace("//insert-imports-here", generatedImports)
Executes the promise and by appending the suffix below 
```
result().then(resp => {
    console.log(resp);
});
```

2022-07-06 20:24 UTC, rkodev commented on TestsCommon/TypeScriptTestRunner.cs
> +        /// <returns></returns>
Lines 341-524 -> Executes the js files by first attempting only Application Access before falling back to delegated access. 
NB: Delegated access is significantly slower. About 220 of the 570+ rely on delegated access

2022-07-06 20:27 UTC, rkodev commented
@zengin Without delegated access the pipeline runs to completion with  a [48% pass rate ](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=79243&view=ms.vss-test-web.build-test-results-tab)

With delegated access enable the pipeline is [not able to execute to completion](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=79374&view=results)

2022-07-06 20:31 UTC, rkodev commented on azure-pipelines/typescript-v1-execution-tests.yml
> +  name: 1es-ubuntu-msgraph-sdk-raptor-compute-latest
Requires more resource , [please check](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=79374&view=results)

Compiling all the tests and elimination of all compilation errors managed to drop execution from 2-3 minutes to about 1-20 seconds.  However this looks like the only option left

2022-07-06 23:15 UTC, zengin requested changes

2022-07-06 23:15 UTC, zengin commented on TestsCommon/TypeScriptTestRunner.cs
> +                    ApplicationAccessTokenCache[isEducation] = tokenValue;
Do we have auth libraries for TS? It might be better to use those to have end-to-end coverage.

2022-07-07 16:07 UTC, fey101 commented on TestsCommon/GoTestRunner.cs
> -     /// <summary>
Any reason for removing this?

2022-07-07 16:09 UTC, fey101 commented on TestsCommon/GoTestRunner.cs
> -     /// <summary>
No worries, seen it's a refactor into TestsCommon.stringsExtensions

2022-07-08 07:40 UTC, merged