Infrastructure for running Get Tests in C# V1 and Beta
microsoftgraph/msgraph-sdk-raptor pull request #156
Opened 2021-01-23 01:02 UTC by zengin

- renamed test run name for compilation tests from `Run` to `Compile`
- introduced a new test type called `Execute`
- created two new projects that call `Execute` (C# V1 and Beta)
- `Execute` test does the following:
  - changes snippet decoration to extract request url for logging purposes
  - creates an Assembly from `Compile` phase
  - creates a ClientCredentialProvider using secrets from `appsettings.json`
  - calls the main method in the generated Assembly using the auth provider
  - if no exception is thrown, the test passes
  - if an exception is thrown, it is logged with the compiled snippet
- added two new pipelines for executing these tests:
  -  [V1 C# Snippet Execution Tests](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=38054&view=ms.vss-test-web.build-test-results-tab)
  -  [Beta C# Snippet Execution Tests](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=38050&view=ms.vss-test-web.build-test-results-tab)
  - Pipelines use secret variables in Azure DevOps and they are fed in to `appsettings.json` file using `scripts/transformAppSettings.ps1` script.
- Test data selection logic ignores known issues of compilation as it doesn't make sense to run those tests for execution (i.e. compilation is a prerequisite for execution)
- added @finsharp as code owner

Note: This PR doesn't address the delegated permissions scenario, it only uses application permissions. Delegated permissions will be addressed with a separate PR.
Fixes #143
Fixes #146

2021-01-25 14:12 UTC, baywet requested changes

2021-01-25 14:12 UTC, baywet commented on azure-pipelines/common-templates/transform-app-settings.yml
> +  - pwsh: '$(Build.SourcesDirectory)/msgraph-sdk-raptor/scripts/transformAppSettings.ps1 -TenantID $(TenantID) -ClientID $(ClientID) -ClientSecret $(ClientSecret)'
nit: I know the work is already done but: couldn't we have used environment variables instead?

2021-01-25 14:12 UTC, baywet commented on scripts/transformAppSettings.ps1
> +    [string]$TenantID,
```suggestion
   [Parameter(Mandatory=$true)][string]$TenantID,
```

2021-01-25 14:12 UTC, baywet commented on scripts/transformAppSettings.ps1
> +    [string]$ClientID,
```suggestion
    [Parameter(Mandatory=$true)][string]$ClientID,
```

2021-01-25 14:12 UTC, baywet commented on scripts/transformAppSettings.ps1
> +    [string]$ClientSecret
```suggestion
    [Parameter(Mandatory=$true)][string]$ClientSecret
```

2021-01-25 14:12 UTC, baywet commented on TestsCommon/CSharpTestRunner.cs
> +                resultVariable = Regex.Match(codeToCompile, resultVariablePattern).Groups[1].Value;
static field for the regex instead? this way it gets compiled only once?

2021-01-25 14:12 UTC, baywet commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphCSharpCompiler.cs
> +                    task.Wait();
any specific reason why this is not using the async/await syntax?

2021-01-25 18:41 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphCSharpCompiler.cs
> +            EmitResult emitResult = compilation.Emit(memoryStream);
Debugging the snippets is out of scope for this PR.

2021-01-25 18:52 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphCSharpCompiler.cs
>                 options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
Thanks for exploring the options here. Default is debug, I will set Release explicitly as we don't have the intentions to debug (at least not yet ;))

2021-01-25 19:11 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphCSharpCompiler.cs
> +                    task.Wait();
yes, I would like to execute the snippet in this try catch block. Adding async/await bubbles up the exception to the caller and handling the exception there requires a lot of refactoring.

We don't have a huge perf hit as all the tests are running parallel and this is very close to the end of a test execution (i.e. test result needs to wait on it anyways).

2021-01-25 19:19 UTC, zengin commented on azure-pipelines/common-templates/transform-app-settings.yml
> +  - pwsh: '$(Build.SourcesDirectory)/msgraph-sdk-raptor/scripts/transformAppSettings.ps1 -TenantID $(TenantID) -ClientID $(ClientID) -ClientSecret $(ClientSecret)'
I have multiple tenants and I use this script locally as well. It is easier to pass in parameters than setting env variables there.

2021-01-25 22:54 UTC, zengin commented on TestsCommon/TestDataGenerator.cs
> +                   select new TestCaseData(executionTestData).SetName(testData.TestName).SetProperty("Owner", testData.TestName);
@finsharp, I looked at this, but the source of categorization is not something consistent in the documentation link. If you find a better source for it, please let me know. Some counter examples:
```
timeoff-put
schedulinggroup-put
site-follow
```

2021-01-26 07:56 UTC, nikithauc commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphCSharpCompiler.cs
> +                    authProvider = new ClientCredentialProvider(confidentialClientApp, "https://graph.microsoft.com/.default");
Can a constant be used for the scope?

2021-01-26 08:06 UTC, nikithauc approved these changes

2021-01-26 13:12 UTC, baywet commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphCSharpCompiler.cs
> +                    task.Wait();
I'm not sure I'm following, there's already a try catch surrounding the block. If you change to async await, and change the type of the exception being caught in the catch right below, won't that do the trick?

2021-01-26 13:14 UTC, baywet commented on azure-pipelines/common-templates/transform-app-settings.yml
> +  - pwsh: '$(Build.SourcesDirectory)/msgraph-sdk-raptor/scripts/transformAppSettings.ps1 -TenantID $(TenantID) -ClientID $(ClientID) -ClientSecret $(ClientSecret)'
locally: $env:MY_TENANT_ID = "id", CI use the env node. It ain't that hard :D but sure, I get it's a preference thing as well.

2021-01-26 13:16 UTC, baywet commented on scripts/transformAppSettings.ps1
> +   [Parameter(Mandatory=$true)][string]$TenantID,
woot! I caught @zengin making a space mistake !!!! 🎉🎉🎉🎉🎉🎉

2021-01-26 13:18 UTC, baywet commented on scripts/transformAppSettings.ps1
> +   [Parameter(Mandatory=$true)][string]$TenantID,
my bad, it's actually my suggestion that introduced it. I'll celebrate another time then.

2021-01-26 13:18 UTC, baywet commented on scripts/transformAppSettings.ps1
> +   [Parameter(Mandatory=$true)][string]$TenantID,
```suggestion
    [Parameter(Mandatory=$true)][string]$TenantID,
```

2021-01-26 18:28 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphCSharpCompiler.cs
> +                    task.Wait();
I got confused. I was trying to figure out why it was bubbling up and it was in front of me the whole time: the specific type in the catch block. Thanks for highlighting that! Will push the fix in a few moments.

2021-01-26 19:01 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphCSharpCompiler.cs
> +                    task.Wait();
fixed

2021-01-26 19:01 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphCSharpCompiler.cs
> +                    authProvider = new ClientCredentialProvider(confidentialClientApp, "https://graph.microsoft.com/.default");
fixed

2021-01-26 19:11 UTC, finsharp approved these changes

2021-01-26 19:35 UTC, baywet approved these changes

2021-01-26 20:18 UTC, merged