Initial TenantSetup Infrastructure Using Pester
microsoftgraph/msgraph-sdk-raptor pull request #219
Opened 2021-03-30 17:15 UTC by finsharp

Initial TenantSetup scripts and infra using Pester to drive the tests.

2021-03-30 23:18 UTC, MIchaelMainer commented on scripts/TenantSetup/Populate-Tenant.ps1
> +    #Connect-AzAccount
Is there a reason to leave this commented out? Either remove, or provide a comment why this is here.

2021-03-30 23:18 UTC, MIchaelMainer commented on scripts/TenantSetup/Populate-Tenant.ps1
> +        $contactFolder = Get-MgUserContactFolder
I'm curious, does Get-MgUserContactFolder use the context of the user who ran Connect-MgGraph?

2021-03-30 23:18 UTC, MIchaelMainer commented on scripts/TenantSetup/loadEnv.ps1
> +    $env.MsGraphTenantIdentifier = ${env:MSGRAPHTENANTIDENTIFIER}
Consider raising an error in case these required environment variables aren't present. Error message should provide clear instructions on what variables need to be set in the environment.

2021-03-31 12:36 UTC, baywet commented on scripts/TenantSetup/Install-Tools.ps1
> +        Install-Module Microsoft.Graph -Force
maybe install in the current user scope instead? installing globally requires admin permissions and depending on the CI platform we might not have that privilege

2021-04-22 23:54 UTC, zengin commented on scripts/TenantSetup/TenantHttpData/Users/POST/user.http
> +    "password": "<password>"
Thanks for making this change. We can also consider adding logic to automatically replace these with values from the test environment.

Given that you already have an envFile, we can maybe use that.

2021-04-23 13:01 UTC, baywet requested changes

2021-04-23 13:01 UTC, baywet commented on scripts/TenantSetup/loadEnv.ps1
> +    $env.MsGraphClientIdentifier = ${env:MSGRAPHCLIENTIDENTIFIER}
nit: use underscore for environment variable names to improve readability

2021-04-26 07:12 UTC, finsharp commented on scripts/TenantSetup/loadEnv.ps1
> +    $env.MsGraphClientIdentifier = ${env:MSGRAPHCLIENTIDENTIFIER}
Given that these variables will come from Azure Devops for example, where its common to state them as `$env:SOME_VARIABLE`, wouldn't be ideal to be consistent with that pattern?

2021-04-26 12:15 UTC, baywet commented on scripts/TenantSetup/loadEnv.ps1
> +    $env.MsGraphClientIdentifier = ${env:MSGRAPHCLIENTIDENTIFIER}
I'm not sure I've seen a convention for ADO. For GitHub people largely use underscores for readability as far as I can tell. Again it's a small thing but I think it'd improve readability. And we can name the variables whatever we want in effects. QQ: were those variable names set before you started the PS work or did you create those?

2021-04-26 18:34 UTC, zengin approved these changes

2021-04-27 11:55 UTC, baywet approved these changes

2021-04-27 14:52 UTC, merged