Fey101/known issues 05 17
microsoftgraph/msgraph-sdk-raptor pull request #265
Opened 2021-05-21 07:17 UTC by fey101

2021-05-21 11:53 UTC, baywet approved these changes

2021-05-21 16:35 UTC, zengin requested changes

2021-05-21 16:35 UTC, zengin commented on TestsCommon/TestDataGenerator.cs
> +                { "update-deployment-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, NamespaceOdataTypeAnnotationsWithoutHashSymbol)},
Because you have a proposal to rename the block names, please include those in this as well so that you don't have to add them after the documentation folks deduplicate the blocks. Having extra entries do not cause any harm, because we only pick up the ones that are referenced in the docs repo.
```suggestion
                { "update-deployment-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, NamespaceOdataTypeAnnotationsWithoutHashSymbol)},
                { "update-deployment-1-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, NamespaceOdataTypeAnnotationsWithoutHashSymbol)},
                { "update-deployment-2-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, NamespaceOdataTypeAnnotationsWithoutHashSymbol)},
```

2021-05-24 16:20 UTC, fey101 commented on TestsCommon/TestDataGenerator.cs
> +                { "update-deployment-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, NamespaceOdataTypeAnnotationsWithoutHashSymbol)},
I went ahead to update this then noticed beta had some other 20 new know issues. So I have added those as well. For now most of them need further analysis

2021-05-26 00:29 UTC, zengin approved these changes

2021-05-26 19:31 UTC, merged