Read demo tenant and update identifiers.json
microsoftgraph/msgraph-sdk-raptor pull request #272
Opened 2021-06-02 11:11 UTC by zengin

Fixes #271 
Fixes #255

- Creates two Powershell scripts that query existing data in the default data pack.
- Adds the template identifier replacement JSON file
- In local run, the template identifier JSON file is used so that local testing can skip relying on the blob storage.
- Adds more APIs that require delegated permissions. (#164 still needs to be addressed separately) 
- Data that need to be explored are left out as comments intentionally to guide us for pushing those missing data in the next phase of development.

2021-06-02 13:43 UTC, fey101 requested changes
Just a few comments on order of params and update for directoryRoleTemplate

2021-06-02 13:43 UTC, fey101 commented on scripts/readDefaultData.ps1
> +        [string]$url
We could reorder params such that required params comes first then default params.

2021-06-02 13:43 UTC, fey101 commented on scripts/readDefaultData.ps1
> +$identifiers.directoryRole._value = $directoryRoleTemplate.id
Did you intend to set the directoryRoleTemplate here instead of directoryRole? This would otherwise overwrite the value in line 134 above.

2021-06-02 13:43 UTC, fey101 commented on scripts/readDefaultData.ps1
> +    $response = Invoke-MgGraphRequest -Headers $headers -Method GET -Uri "https://graph.microsoft.com/$version/$url" -OutputType PSObject
What happens if request fails due to network issues? could we provide a fail safe for this case?

2021-06-02 13:43 UTC, fey101 commented on scripts/readDefaultDataDelegated.ps1
> +        [string]$url,
Order of param such that required param comes first.

2021-06-02 21:32 UTC, zengin commented on scripts/readDefaultData.ps1
> +    $response = Invoke-MgGraphRequest -Headers $headers -Method GET -Uri "https://graph.microsoft.com/$version/$url" -OutputType PSObject
We can rerun the full script in that case because rerunning the full script shouldn't affect the end result. In other words if we fail to update <type-id>, than <type-id> can be updated in a subsequent run.

2021-06-02 21:33 UTC, zengin commented on scripts/readDefaultData.ps1
> +$identifiers.directoryRole._value = $directoryRoleTemplate.id
nice catch, thanks!

2021-06-02 21:33 UTC, zengin commented on scripts/readDefaultData.ps1
> +        [string]$url
thanks, updated.

2021-06-02 21:34 UTC, zengin commented on scripts/readDefaultDataDelegated.ps1
> +        [string]$url,
thanks, updated.

2021-06-02 21:38 UTC, georgend approved these changes

2021-06-03 08:07 UTC, fey101 approved these changes

2021-06-03 08:07 UTC, merged

2021-06-07 15:32 UTC, fey101 commented
Closes https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/251