Add Script and Data for Policy Related Entities
microsoftgraph/msgraph-sdk-raptor pull request #280
Opened 2021-06-10 17:23 UTC by georgend

Adds Scripts and data to Populate Tenant with the following data if doesn't exist/
- ActivityBasedTimeoutPolicy
- ClaimsMappingPolicy
- HomeRealDiscoveryPolicy
- TokenIssuancePolicy

2021-06-10 17:58 UTC, baywet commented on scripts/TenantSetup/TenantHttpData/Policy/Policy.ps1
> +function Get-RequestData {
these methods are duplicated with #279 , please move that to a another file and reference in both

2021-06-10 17:58 UTC, baywet requested changes

2021-06-10 17:58 UTC, baywet commented on scripts/TenantSetup/TenantHttpData/Policy/Policy.ps1
> +function Get-RequestData {
these methods are duplicated with #279 , please move that to a another file and reference in both

2021-06-10 18:03 UTC, georgend commented on scripts/TenantSetup/TenantHttpData/Policy/Policy.ps1
> +function Get-RequestData {
Noted, we are handling this.

2021-06-16 12:32 UTC, baywet approved these changes

2021-06-16 14:56 UTC, fey101 approved these changes

2021-06-16 15:05 UTC, merged