Handle Verbatim Identifiers such as @event
microsoftgraph/msgraph-sdk-raptor pull request #286
Opened 2021-06-15 18:25 UTC by georgend

Currently Raptor incorrectly handles verbatim identifiers due to the Regex used to handle variable replacement. 
This PR changes the regex to correctly handle `@event`, `_event` and `@_event`.
Check if Regex passes when replacing variables in C# test runner, throws and reports the error.
Add tests to verify various cases for verbatim identifiers.

2021-06-15 18:40 UTC, baywet requested changes

2021-06-15 18:40 UTC, baywet commented on TestsCommon/CSharpTestRunner.cs
> +                var resultVariableMatch = ResultVariableRegex.Match(codeToCompile);
refactor to a method with the one below to avoid duplication

2021-06-15 18:40 UTC, baywet commented on TestsCommon/CSharpTestRunner.cs
> +                    Assert.Fail("Regex {0}, against code {1} Failed", ResultVariablePattern, codeToCompile);
this is going to be caught by the catch and wrapper, was it intended this way? if so why not using a plain exception?

2021-06-15 18:47 UTC, fey101 commented on UnitTests/CSharpTestRunnerTests.cs
> +            CSharpTestRunner.CaptureUriAndHeadersInException(testSnippet);
Are we asserting anything in this test "ShouldCaptureUriAndHeadersInException"

2021-06-15 18:56 UTC, fey101 requested changes
LGTM. Just a few comments on some tests that lack assertions. Otherwise, well done.

2021-06-15 18:56 UTC, fey101 commented on UnitTests/CSharpTestRunnerTests.cs
> +            CSharpTestRunner.ReturnHttpRequestMessage(testSnippet);
We should assert that it returns httpRequestMessage in some way, the first line of the returned string or any other portion of it.

2021-06-15 18:56 UTC, fey101 commented on TestsCommon/CSharpTestRunner.cs
> +        internal static readonly Regex ResultVariableRegex = new Regex(ResultVariablePattern, RegexOptions.Singleline | RegexOptions.Compiled);
🥇 Am happy to see the usecase for internal access modifier. Learnt something new.

2021-06-15 19:01 UTC, fey101 commented on TestsCommon/CSharpTestRunner.cs
> +                    Assert.Fail("Regex {0}, against code {1} Failed", ResultVariablePattern, codeToCompile);
I think it's intended so that it doesn't stop the rest of the raptor e2e tests from executing owing to the way the tests are structured such that it's basically a single test encompassing the tests for all the available code snippets. And given that raptor is generally a test case in it's structure maybe assert.Fail is the right approach.

2021-06-15 20:15 UTC, georgend commented on UnitTests/CSharpTestRunnerTests.cs
> +            CSharpTestRunner.ReturnHttpRequestMessage(testSnippet);
I will use `Assert.DoesNotThrow()` to confirm that no exception is thrown by the call.

2021-06-16 12:19 UTC, baywet approved these changes

2021-06-16 13:45 UTC, fey101 approved these changes

2021-06-16 13:45 UTC, merged