Fey 101/fill missing data part 1
microsoftgraph/msgraph-sdk-raptor pull request #289
Opened 2021-06-17 11:36 UTC by fey101

- Rearrage functions in `RaptorUtils.ps1` so that the get app settings related functions move to the top with no changes made to functions themselves.
- Added `reqDelegated` and `getToken` functions to `RaptorUtils.ps1` file
- Add identifiers.json and appsettings.json to gitignored files. There could be need to run the following command in local to clear git-tracking for this files
```bash
git update-index --assume-unchanged .\msgraph-sdk-raptor-compiler-lib\appsettings.json
git update-index --assume-unchanged .\msgraph-sdk-raptor-compiler-lib\identifiers.json
```
- Adds scripts to fill in missing data for 
     - chat
         - chat
         - conversationMember
         - teamsTab
         - installedApps
     - dataPolicyOperations
     - threatAssessmentRequest

2021-06-17 16:51 UTC, baywet requested changes

2021-06-17 16:51 UTC, baywet commented on scripts/TenantSetup/RaptorUtils.ps1
> +function getToken
naming conventions: get-token

2021-06-17 16:51 UTC, baywet commented on scripts/TenantSetup/RaptorUtils.ps1
> +    $tokenEndpoint = "https://login.microsoftonline.com/$domain/oauth2/v2.0/token"
can't we use the ps sdk to do that for us instead of crafting the request manually? CC @peombwa

2021-06-17 16:51 UTC, baywet commented on scripts/TenantSetup/RaptorUtils.ps1
> +function reqDelegated
naming convnetions

2021-06-17 18:04 UTC, fey101 commented on scripts/TenantSetup/RaptorUtils.ps1
> +    $tokenEndpoint = "https://login.microsoftonline.com/$domain/oauth2/v2.0/token"
We cant because ps sdk does not support delegated permissions for an app. So to bypass the need for user interaction when requesting delegated permission, we craft it manually.

2021-06-17 19:28 UTC, baywet commented on scripts/TenantSetup/RaptorUtils.ps1
> +    $tokenEndpoint = "https://login.microsoftonline.com/$domain/oauth2/v2.0/token"
thanks for clarifying!

2021-06-17 19:28 UTC, baywet approved these changes

2021-06-17 23:20 UTC, MIchaelMainer requested changes
nit: add copyright headers to all files, add documentation as well.

2021-06-17 23:20 UTC, MIchaelMainer commented on scripts/TenantSetup/RaptorUtils.ps1
> +    $body = "grant_type=$grantType&username=$($appSettings.Username)&password=$($appSettings.Password)&client_id=$($appSettings.ClientID)&scope=$($joinedScopeString)"
Might as well hardcode grantType as password since username and password parameters are only used with password grant.

2021-06-17 23:20 UTC, MIchaelMainer commented on scripts/TenantSetup/RaptorUtils.ps1
> +    $token.access_token
Even though this works as the returned value, for consistency, I suggest a return statement.

`return $token.access_token`

2021-06-18 17:22 UTC, MIchaelMainer approved these changes

2021-06-18 19:34 UTC, merged