Add workbook as a driveItem
microsoftgraph/msgraph-sdk-raptor pull request #313
Opened 2021-07-13 16:21 UTC by fey101

2021-08-06 18:21 UTC, georgend requested changes

2021-08-06 19:56 UTC, fey101 commented on scripts/TenantSetup/RaptorUtils.ps1
> +    if ($FilePath) {
Added.

2021-08-06 21:40 UTC, MIchaelMainer commented on scripts/TenantSetup/RaptorUtils.ps1
> +        $response = Invoke-MgGraphRequest -Method $Method -Headers $Headers -Uri "https://graph.microsoft.com/$Version/$Uri" -InputFilePath $FilePath -OutputType PSObject -ResponseHeadersVariable "re
nit: `$Uri` is actually a relative URI, consider renaming it `$RelativeUri`

2021-08-06 21:40 UTC, MIchaelMainer commented on scripts/TenantSetup/TenantHttpData/driveItem/driveItem.ps1
> +if($null -eq $driveItem) {
global comment

Is it possible that these variables could already be set in the PowerShell context where this script runs? If so, we could have some unexpected behavior. Would it make sense for us to raise a warning message if these variables are already set when this script runs?

2021-08-07 01:05 UTC, zengin requested changes

2021-08-07 01:05 UTC, zengin commented on scripts/TenantSetup/TenantHttpData/driveItem/driveItem.ps1
> +if($null -eq $driveItem) {
I think there is some dependency on the order of executing these PowerShell scripts. It was initially only two files, one for application permissions and the other for delegated permissions and we were using values from one script execution in another. It looks like we are expanding that into multiple files here with further categorization and scaling that can be confusing.

This also points to an indeterministic behavior for the output. If both negative and positive cases of the `if` statement can be true in different executions, we are outputting two different `identifiers.json` files which is unexpected.

I think we should make the execution order more explicit either by putting everything into a single file or some other mechanism.

2021-08-07 01:05 UTC, zengin commented on scripts/TenantSetup/TenantHttpData/printer/printer.ps1
> +if($null -eq $printer) {
@MIchaelMainer's comment holds here too.

2021-08-07 01:05 UTC, zengin commented on scripts/TenantSetup/TenantHttpData/printer/printer.ps1
> +    $storedSecretContent = Get-AzKeyVaultSecret -VaultName $appSettings.AzureKeyVaultName -Name "csrData" -AsPlainText
Please add a comment here explaining what we are achieving by calling these APIs.

2021-08-07 01:57 UTC, fey101 commented on scripts/TenantSetup/RaptorUtils.ps1
> +    if ($FilePath -and (Test-Path -Path $FilePath)) {
$FilePath is optional. Having Test-Path alone would make it mandatory.

2021-08-07 02:16 UTC, fey101 commented on scripts/TenantSetup/RaptorUtils.ps1
> +        $response = Invoke-MgGraphRequest -Method $Method -Headers $Headers -Uri "https://graph.microsoft.com/$Version/$Uri" -InputFilePath $FilePath -OutputType PSObject -ResponseHeadersVariable "re
@MIchaelMainer , this would affect lots of files that all pass the parameter $Uri. Could I handle this in a subsequent PR to reduce number of moving parts? I could create an issue and handle it as a separate PR from this one.

2021-08-07 02:19 UTC, fey101 commented on scripts/TenantSetup/TenantHttpData/driveItem/driveItem.ps1
> +if($null -eq $driveItem) {
With how the scripts work, it's okay to have the variables already set as it means the data had already been worked on/created for that particular variable. And if this is the case, there's no harm in avoiding subsequent http calls and relying on the data that was already there.

2021-08-07 02:42 UTC, fey101 commented on scripts/TenantSetup/TenantHttpData/driveItem/driveItem.ps1
> +if($null -eq $driveItem) {
@zengin , the idea is still the same, in that everything that depends on driveItem is now in a single script. Which means the order of executing dependant scripts is implied. If printer for example was to influence driveItem.operation like it was initially thought, we'd bundle the printer logic within the driveItem.ps1 script. The only difference is that the expansion into multiple files brought about some modularity so that It's even easier and faster to tell the related/dependant scripts.

2021-08-07 03:45 UTC, fey101 commented on scripts/TenantSetup/TenantHttpData/printer/printer.ps1
> +if($null -eq $printer) {
Fixed.

2021-08-07 03:46 UTC, fey101 commented on scripts/TenantSetup/TenantHttpData/driveItem/driveItem.ps1
> +if($null -eq $driveItem) {
Additionally, I have removed the if blocks so that if driveItem changes everything below it is executed as well.

2021-08-09 19:33 UTC, zengin commented on scripts/TenantSetup/RaptorUtils.ps1
> +        $response = Invoke-MgGraphRequest -Method $Method -Headers $Headers -Uri "https://graph.microsoft.com/$Version/$Uri" -InputFilePath $FilePath -OutputType PSObject -ResponseHeadersVariable "re
@fey101 Relative URIs qualify as URIs, they are a special kind though. I agree that we should clarify that in the name, but I think it can be postponed. Please create an issue so that we don't forget.

2021-08-09 19:37 UTC, zengin approved these changes

2021-08-10 01:10 UTC, fey101 commented on scripts/TenantSetup/RaptorUtils.ps1
> +        $response = Invoke-MgGraphRequest -Method $Method -Headers $Headers -Uri "https://graph.microsoft.com/$Version/$Uri" -InputFilePath $FilePath -OutputType PSObject -ResponseHeadersVariable "re
https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/365

2021-08-11 18:27 UTC, georgend approved these changes

2021-08-11 18:27 UTC, merged