Permissions Issue: Accepted Senders Only has Delegated Permissions.
microsoftgraph/msgraph-sdk-raptor pull request #360
Opened 2021-08-06 14:04 UTC by georgend

Add Groups["{guid}"].AcceptedSenders to list of Delegated permission endpoints since endpoint does not support Application Permissions.
- List Accepted Senders - https://docs.microsoft.com/en-us/graph/api/group-list-conversations?view=graph-rest-1.0&tabs=http
![image](https://user-images.githubusercontent.com/1641829/128522303-880fb200-f976-4809-8c35-f2b75d297ebd.png)

Add various compilations options.

2021-08-06 20:47 UTC, MIchaelMainer requested changes

2021-08-06 20:47 UTC, MIchaelMainer commented on msgraph-sdk-raptor-compiler-lib/Models/TestsSetup.cs
> +        public static void CleanupPublicClientApp(IConfidentialClientApplication confidentialClientApplication)
Likely meant for this to be called `CleanupConfidentialClientApp`

2021-08-09 19:39 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphCSharpCompiler.cs
> +            EmitResult emitResult = compilation.Emit(memoryStream, options: new EmitOptions(metadataOnly: false, DebugInformationFormat.Embedded));
Q: how do we consume this debug information?

2021-08-10 14:49 UTC, georgend commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphCSharpCompiler.cs
> +            EmitResult emitResult = compilation.Emit(memoryStream, options: new EmitOptions(metadataOnly: false, DebugInformationFormat.Embedded));
Step in debugging of the actual snippet during test debugging sessions.

2021-08-17 22:57 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphCSharpCompiler.cs
> +            EmitResult emitResult = compilation.Emit(memoryStream, options: new EmitOptions(metadataOnly: false, DebugInformationFormat.Embedded));
Ah, cool.

2021-08-17 23:27 UTC, zengin approved these changes

2021-08-18 00:28 UTC, merged