Move csharp new known issues from stable tests
microsoftgraph/msgraph-sdk-raptor pull request #421
Opened 2021-09-09 16:20 UTC by fey101

Most of these tests are failing with the error 

"System.IO.InvalidDataException : no data found for id: {termStore.group-id} in identifiers.json file". 

For the above case, I know for example call records is still in our [todo issue list](https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/320) data hasn't been created yet. Not sure how they were passing before. For these tests I have categorized them as "MissingDataKnownIssue"

A few others are failing with the error:

"Can't get scopes for both delegated and application scopes (The JSON value could not be converted to MsGraphSDKSnippetsCompiler.Models.Scope[]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.)
The JSON value could not be converted to MsGraphSDKSnippetsCompiler.Models.Scope[]. Path: $ | LineNumber: 0 | BytePositionInLine: 1."

For the ones failing with can't get scopes, I have categorized as "NeedsAnalysisKnownIssue"

2021-09-09 16:51 UTC, baywet approved these changes

2021-09-09 16:55 UTC, zengin requested changes
Please mark the tests that can't get the scopes from DevX API as `MissingPermissionScopeKnownIssue`.

2021-09-09 17:50 UTC, zengin approved these changes

2021-09-10 03:42 UTC, georgend approved these changes

2021-09-10 03:42 UTC, merged