Features/unified app config
microsoftgraph/msgraph-sdk-raptor pull request #427
Opened 2021-09-10 05:21 UTC by georgend

2021-09-10 10:58 UTC, baywet commented
Hey @georgend this pr is conflicting, can you rebase and solve before we review please?

2021-09-10 16:53 UTC, zengin requested changes
Thanks George, this will be a really helpful change and will save us a lot of time. A few points:

- [ ] This change breaks some of the pipelines. Please search for all references to Test.runsettings. You will see that one of the files you removed is used for end to end pipeline for staging.
- [ ] PR checks are also failing due to missing new pipeline variable.
- [ ] Please also make sure to remove all the old appsettings logic as part of this PR. Transform app settings etc.
- [ ] Please make sure that all pipelines listed under `Raptor` in Azure DevOps runs in your branch successfully, including the new weekly app deployment for delegated permissions.

Thanks!

2021-09-10 17:32 UTC, baywet requested changes

2021-09-10 17:32 UTC, baywet commented on msgraph-sdk-raptor-compiler-lib/msgraph-sdk-raptor-compiler-lib.csproj
> +        <PackageReference Include="Microsoft.Graph" Version="4.4.0" />
any specific reason why we're going back on versions here? looks like a bad merge

2021-09-13 14:29 UTC, baywet approved these changes

2021-09-13 17:57 UTC, zengin approved these changes

2021-09-13 17:57 UTC, merged