Fix get or create in chat.ps1, datapolicyoperation.ps1, driveItem.ps1
microsoftgraph/msgraph-sdk-raptor pull request #530
Opened 2021-10-25 13:25 UTC by fey101

Do a get or create for the scripts so that we only create if object doesn't exist.

For task trigger, there's a known issue where despite live view returning an empty array, the creation phase fails with error message task trigger already exists. Related issue here https://github.com/microsoftgraph/microsoft-graph-docs/issues/14774

Closes #493 , resolves #494, resolves #491, resolves #488

2021-11-01 23:35 UTC, fey101 commented on scripts/TenantSetup/TenantHttpData/dataPolicyOperation/dataPolicyOperation.ps1
> +$dataPolicyOperationContent = Get-RequestData -ChildEntity "dataPolicyOperation"
There is no list endpoint for dataPolicyOperation hence we will need to create every time.

2021-11-02 12:25 UTC, georgend requested changes

2021-11-02 12:26 UTC, georgend commented
Have you run these changes in the context of InitTenant.ps1 script. As part of the wholly integrated tenant script?

2021-11-02 12:30 UTC, georgend commented on scripts/TenantSetup/TenantHttpData/dataPolicyOperation/dataPolicyOperation.ps1
> +$exportDataRequest = az storage blob exists --container-name exportpersonaldatastorage --name RequestInfo.json --connection-string $appSettings.AzureStorageConnectionString
Is `AzureStorageConnectionString` already added to our Azure AppConfig?

2021-11-02 12:32 UTC, fey101 commented on scripts/TenantSetup/TenantHttpData/driveItem/driveItem.ps1
> +    driveItemWorkbookOperation = Request-DelegatedResource -Uri "/me/drive/items/$($driveItem.id)/workbook/operations/$($currentOperationId)"
Nice catch. Thanks

2021-11-02 14:43 UTC, fey101 commented on scripts/TenantSetup/TenantHttpData/dataPolicyOperation/dataPolicyOperation.ps1
> +$exportDataRequest = az storage blob exists --container-name exportpersonaldatastorage --name RequestInfo.json --connection-string $appSettings.AzureStorageConnectionString
It is the same value for RaptorStorageConnectionString so I have switched to using the commonly used name in the updated changes. That makes azureStorageConnectionString irrelevant.

2021-11-02 18:35 UTC, georgend approved these changes

2021-11-02 19:19 UTC, merged