Add PSScript Analyzer to lint powershell scripts
microsoftgraph/msgraph-sdk-raptor pull request #681
Opened 2021-11-25 09:53 UTC by georgend

Use PSSCript Analyzer to lint and report issues with the growing number of PowerShell Scripts.

2021-11-25 12:32 UTC, baywet approved these changes

2021-11-25 14:01 UTC, baywet approved these changes

2021-11-25 14:44 UTC, fey101 commented on scripts/TenantSetup/RaptorUtils.ps1
> +[System.Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingConvertToSecureStringWithPlainText', '', Scope='Function', Target='Get-HtmlDataRequest')]
This does not look neat. Is there a better way to do the same like having a linter-specific file where the unapplicable rules are suppressed?

2021-11-25 14:55 UTC, fey101 commented on scripts/TenantSetup/RaptorUtils.ps1
> -        [Parameter(Mandatory = $False)][ValidateSet("GET", "POST", "PUT", "PATCH", "DELETE")][string] $Method = "GET",
Beauty of having linters that can quickly discover unused params. 👏🏽

2021-11-25 15:01 UTC, fey101 commented on scripts/generateCSharpModels.ps1
> +Write-Output "Transformed $metadataFile to $cleanMetadataFile" -ForegroundColor Green
with the Write-Host command, you can decorate the output with Foreground and Background color, and this is not possible with the Write-Output cmdlet.

2021-11-25 15:04 UTC, fey101 commented on scripts/TenantSetup/InitTenant.ps1
> +    Write-Output "Executing $scriptName at $scriptPath" -ForegroundColor Green
with the Write-Host command, you can decorate the output with Foreground and Background color, and this is not possible with the Write-Output cmdlet. Any reason why you prefer write-output to write-host? I see "Write-Output sends the text as an object to the next pipeline command. If no later pipeline command is provided, the Write-Output also outputs the text to the screen." [source:here](https://morgantechspace.com/2021/02/write-output-vs-write-host-in-powershell.html) but I don't this this is the intention in these scripts?

2021-11-25 15:07 UTC, fey101 requested changes
The linter is a great idea. Left a couple of comments.

2021-11-27 09:12 UTC, georgend commented on scripts/TenantSetup/InitTenant.ps1
> +    Write-Output "Executing $scriptName at $scriptPath" -ForegroundColor Green
Added a new method `Write-ColorOutput` that correctly handles color output before calling `Write-Output`

2021-11-27 09:14 UTC, georgend commented on scripts/TenantSetup/RaptorUtils.ps1
> +[System.Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingConvertToSecureStringWithPlainText', '', Scope='Function', Target='Get-HtmlDataRequest')]
My thoughts were that suppressions should be close to the suppression point, and in this case the closest to the suppression point is at the top of the file.

2021-11-29 09:39 UTC, fey101 commented on scripts/TenantSetup/RaptorUtils.ps1
> +[System.Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingConvertToSecureStringWithPlainText', '', Scope='Function', Target='Get-HtmlDataRequest')]
Are there common suppression that cut across files? Should they be in a single file? For PSScriptAnalyzer, the file is called `PSScriptAnalyzerSettings.psd1` . I found a script that talks about the goal am hoping we can achieve here https://devblogs.microsoft.com/scripting/visual-studio-code-editing-features-for-powershell-development-part-2/#psscriptanalyzer-integration

2021-11-29 09:57 UTC, fey101 commented on scripts/applyReadPermissionsToManifest.ps1
> +Write-Output "Updated manifest file with $countDelegated delegated and $countApplication application permissions!" -ForegroundColor Green
Did you forget to update this to use Write-ColorOutput

2021-11-29 09:57 UTC, fey101 commented on scripts/generateCSharpModels.ps1
> +Write-Output "Downloaded $env:MetadataURL to $metadataFile" -ForegroundColor Green
Did you forget to update this to use Write-ColorOutput?

2021-11-29 09:58 UTC, fey101 commented on scripts/generateCSharpModels.ps1
> +Write-Output "Transformed $metadataFile to $cleanMetadataFile" -ForegroundColor Green
Did you forget to update this to use Write-ColorOutput?

2021-11-29 09:59 UTC, fey101 reviewed
Did you forget to update the lines that specify color to use Write-ColorOutput?

2021-11-29 10:00 UTC, georgend commented on scripts/generateCSharpModels.ps1
> +Write-Output "Downloaded $env:MetadataURL to $metadataFile" -ForegroundColor Green
Yes. I missed this one.

2021-11-29 13:24 UTC, baywet approved these changes

2021-11-29 13:26 UTC, fey101 commented on scripts/TenantSetup/InitTenant.ps1
> +    Write-ColorOutput -ForegroundColor Green "Executing $scriptName at $scriptPath"
@georgend , wouldn't it be much easier to use the exclude rule in  PSScriptAnalyzerSettings.psd1 file as show in attached screenshot instead of writing a function to replace `Write-Host`? Not unless Write-Host has negative side effects that we would like to avoid by using write-output. Which doesn't seem to be the case 
![image](https://user-images.githubusercontent.com/11347476/143876102-8c9c7e74-ce22-441e-b696-de22c9b8cdf1.png)

2021-11-30 00:59 UTC, zengin commented on scripts/TenantSetup/InitTenant.ps1
> +    Write-ColorOutput -ForegroundColor Green "Executing $scriptName at $scriptPath"
Based on the conversation here, I think we can continue using `Write-Host` for this particular set of scripts: https://github.com/PowerShell/PSScriptAnalyzer/issues/1118

But if the color is not adding too much value, we can just switch to `Write-Output` too. So I am OK for both :)

2021-11-30 11:36 UTC, fey101 approved these changes

2021-11-30 11:36 UTC, merged