Feature/add typescript tests
microsoftgraph/msgraph-sdk-raptor pull request #699
Opened 2021-12-06 14:20 UTC by rkodev

Adds typescript test to Raptor

2021-12-06 14:43 UTC, baywet requested changes
This is great! a couple of minor comments

2021-12-06 14:43 UTC, baywet commented on TestsCommon/TypeScriptTestRunner.cs
> +        private const string authProviderCurrent = @"class Auth extends BaseBearerTokenAuthenticationProvider {
You shouldn't need that, the AzureIdentityAuthenticationProvider does that for you.

2021-12-06 14:43 UTC, baywet commented on TypeScriptBetaTest/TypeScriptBetaTest.csproj
> +    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
those deps are outdated, run `dotnet outdated -u` (and if you don't have the tool `dotnet tool install -g outdated`

2021-12-07 11:14 UTC, fey101 reviewed
💯 pretty clean. Well done. LGTM

2021-12-07 12:27 UTC, georgend commented
https://github.com/microsoftgraph/msgraph-sdk-raptor/blob/59d98cf4df6d357138d3c69e40ef0bb70a564583/TestsCommon/RunSettings.cs#L66-L78

Mapping needed for TypeScript or do we coerce to JavaScript?

2021-12-07 13:12 UTC, baywet commented
> Should we coerce TypeScript to JavaScript?

What do you mean by that?

2021-12-08 07:53 UTC, georgend commented
> > Should we coerce TypeScript to JavaScript?
> 
> What do you mean by that?

@rkodev elaborated the requirements for the feature, it requires a special branch of the docs with typescript snippets. I meant should we assume force js snippets to be run when TypeScript is specified. I have been correctly advised now.

2021-12-08 12:20 UTC, rkodev commented on TestsCommon/TypeScriptTestRunner.cs
> +        private const string authProviderCurrent = @"class Auth extends BaseBearerTokenAuthenticationProvider {
Done

2021-12-08 12:20 UTC, rkodev commented on TypeScriptBetaTest/TypeScriptBetaTest.csproj
> +    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
Done

2021-12-08 12:22 UTC, rkodev commented
I've added set up instructions and rebased this pr

2021-12-08 13:24 UTC, baywet requested changes

2021-12-08 13:24 UTC, baywet commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphTypescriptCompiler.cs
> +        private static async Task PrepareProjectFolder(string sourceFileDirectory)
remove the async and return a completed task

2021-12-08 13:24 UTC, baywet commented on msgraph-sdk-raptor-compiler-lib/Models/RaptorConfig.cs
> +    public string TypeScriptFolder
add a comment this needs to be removed when the lib is published

2021-12-08 13:42 UTC, rkodev commented on msgraph-sdk-raptor-compiler-lib/Models/RaptorConfig.cs
> +    public string TypeScriptFolder
Yes, we will migrate to using a temporary folder for the tests

2021-12-08 13:51 UTC, rkodev commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphTypescriptCompiler.cs
> +        private static async Task PrepareProjectFolder(string sourceFileDirectory)
@baywet In this case, can we simply execute this on the same thread, leave it as a `static void` method

2021-12-08 13:54 UTC, baywet commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphTypescriptCompiler.cs
> +        private static async Task PrepareProjectFolder(string sourceFileDirectory)
sorry, early morning for me, didn't notice it was private, I thought this method was interface implementation. yep, void works even better.

2021-12-08 19:25 UTC, zengin requested changes

2021-12-08 19:25 UTC, zengin commented on README.md
> +2. Build the solution
keeping all these as 1s make is easier to move items up and down. When the markdown is rendered, the correct numbers are displayed.

2021-12-08 19:25 UTC, zengin commented on TypeScriptBetaTest/SnippetCompileBetaTests.cs
> +namespace TypeScriptBetaTest
The project name / folder name / namespace should be plural `TypeScriptBetaTests` to match with other projects.

2021-12-08 19:25 UTC, zengin commented on TypeScriptBetaTest/SnippetCompileBetaTests.cs
> +        public static IEnumerable<TestCaseData> TestDataV1 => TestDataGenerator.GetTestCaseData(
Beta project references V1 data. It should point to Beta test data.

2021-12-08 19:25 UTC, zengin commented on TypeScriptBetaTest/SnippetCompileBetaTests.cs
> +                Version = Versions.V1,
```suggestion
                Version = Versions.Beta,
```

2021-12-08 19:25 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphTypescriptCompiler.cs
> +                    File.Delete(Path.Combine(sourceFileDirectory, cleanUpFile));
no need to check whether file doesn't exist. No exception is thrown if the file doesn't exist: https://docs.microsoft.com/en-us/dotnet/api/system.io.file.delete?view=net-6.0#remarks

2021-12-08 19:25 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphTypescriptCompiler.cs
> +            lock (versionLock)
`MicrosoftGraphTypescriptCompiler` will never have different versions in the current project setup. We have one object per snippet.

2021-12-08 19:25 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphTypescriptCompiler.cs
> +            if (!currentlyConfiguredVersion.HasValue || currentlyConfiguredVersion.Value != version)
same `MicrosoftGraphTypescriptCompiler` object lifetime comment as above.

2021-12-08 19:25 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphTypescriptCompiler.cs
> +                    FileName = "powershell",
calling tsc directly should be doable. Let me know if you want to sync on this.

2021-12-08 19:25 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphTypescriptCompiler.cs
> +        private const string errorsSuffix = "error";
please move readonly and constant values to the top, before the constructors/methods.

2021-12-08 19:25 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphTypescriptCompiler.cs
> +                                                                        "TypeScript1000: 'Gradle.Build'",
looks like a copy/paste error. Gradle shouldn't be involved in Typescript.

2021-12-08 19:25 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphTypescriptCompiler.cs
> +        private static void CreateDirectoryStructure(string rootPath, string[] subdirectoriesNames)
Please move this to a shared helper as it is the same for Java and TypeScript.

2021-12-08 19:25 UTC, zengin commented on README.md
> +1. Set thre environment variables, either locally or in your [codespaces settings](https://github.com/settings/codespaces)
Did you want to add a third environment variable here?

2021-12-13 14:30 UTC, baywet commented on msgraph-sdk-raptor-compiler-lib/Models/RaptorConfig.cs
> +    public string TypeScriptFolder
understood that's the plan, I think it needs to be communicated in the source in case we forget in the long run and someone comes back to this. Please add a TODO comment.

2021-12-15 02:50 UTC, zengin requested changes
what is the current plan for adding V1 tests? Please either add them as part of this PR if it is a simple change or create a follow up work item. Ideally both V1 and Beta projects should go in before we attempt to create the pipelines.

2021-12-15 02:50 UTC, zengin commented on msgraph-sdk-raptor.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "TypeScriptBetaTests", "TypeScriptBetaTest\TypeScriptBetaTests.csproj", "{757FC453-510F-4DD2-90F9-D652B026803E}"
please rename the folder for consistency and move the files too.

```suggestion
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "TypeScriptBetaTests", "TypeScriptBetaTests\TypeScriptBetaTests.csproj", "{757FC453-510F-4DD2-90F9-D652B026803E}"
```

2021-12-15 02:50 UTC, zengin commented on TypeScriptBetaTest/SnippetCompileBetaTests.cs
>          public static IEnumerable<TestCaseData> TestDataV1 => TestDataGenerator.GetTestCaseData(
variable name still refers to V1.
```suggestion
        public static IEnumerable<TestCaseData> TestDataBeta => TestDataGenerator.GetTestCaseData(
```

2021-12-15 02:51 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphTypescriptCompiler.cs
> +                    FileName = "powershell",
created this to follow up: https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/723

2021-12-15 14:17 UTC, rkodev commented on msgraph-sdk-raptor-compiler-lib/Models/RaptorConfig.cs
> +    public string TypeScriptFolder
@baywet This is done

2021-12-15 17:40 UTC, zengin approved these changes

2021-12-15 17:43 UTC, baywet approved these changes

2021-12-16 12:56 UTC, merged