Bugfixes/migration bugs
microsoftgraph/msgraph-sdk-raptor pull request #744
Opened 2022-01-04 21:45 UTC by georgend

2022-01-04 22:57 UTC, zengin requested changes

2022-01-04 22:57 UTC, zengin commented on scripts/TenantSetup/RaptorUtils.ps1
> +    if ($Path[0] -ne "/") # DevX API expects a trailing slash
fixing my typo :)
```suggestion
    if ($Path[0] -ne "/") # DevX API expects a leading slash
```

2022-01-04 22:57 UTC, zengin commented on azure-pipelines/typescript-beta-compile-tests.yml
> +# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
please remove this file. Let's not merge two different sets of work in a single PR ;)

2022-01-05 00:35 UTC, georgend commented on azure-pipelines/typescript-beta-compile-tests.yml
> +# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
My bad. Purging

2022-01-10 16:26 UTC, fey101 approved these changes
LGTM

2022-01-10 18:16 UTC, zengin approved these changes

2022-01-10 22:41 UTC, merged