Powershell
microsoftgraph/msgraph-sdk-raptor pull request #752
Opened 2022-01-10 13:06 UTC by georgend

2022-01-11 07:37 UTC, timayabi2020 approved these changes
Tests are executing well

2022-01-13 19:12 UTC, zengin requested changes
Please
- [x] address all the compiler warnings
- [x] create an issue for end-to-end pipeline where everything is from source.
- [x] create an issue for creating a separate set of known issues for PowerShell. Reusing CSharp list kinda makes sense as the initial iteration, but the code is generated in two very different mechanisms, so we should keep a separate list.

2022-01-13 19:12 UTC, zengin commented on TestsCommon/HostedRunspace.cs
> +        // TODO release unmanaged resources here
not implemented

2022-01-13 19:12 UTC, zengin commented on azure-pipelines/powershell-beta-execution-tests-known-issues.yml
> +     ref: snippet-generation/62136
Please create an issue and link it here to address generation of snippets and SDK end-to-end.

2022-01-13 19:12 UTC, zengin commented on azure-pipelines/powershell-beta-execution-tests-known-issues.yml
> +  - task: PowerShell@2
create a template for this task instead of repeating in all pipelines.

2022-01-13 19:12 UTC, zengin commented on azure-pipelines/typescript-beta-compile-tests.yml
> +# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
Please don't merge two different sets of work. Remove this file.

2022-01-13 19:12 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/Models/IdentifierReplacer.cs
> +    public static Regex CsharpIdRegex = new(@"{([A-Za-z0-9\.]+)\-id}", RegexOptions.Compiled);
please either fix the warning here or suppress with a justification.

2022-01-13 20:19 UTC, georgend commented on PowerShellBetaTests/RaptorUtils.ps1
> +﻿# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
We have removed this file.

2022-01-13 20:19 UTC, georgend commented on PowerShellBetaTests/identifiers.json
> +{
We have removed this file.

2022-01-13 20:22 UTC, georgend commented on azure-pipelines/typescript-beta-compile-tests.yml
> +# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
Removed

2022-01-13 22:23 UTC, georgend commented on azure-pipelines/powershell-beta-execution-tests-known-issues.yml
> +     ref: snippet-generation/62136
-  https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/764

2022-01-13 22:24 UTC, georgend commented on msgraph-sdk-raptor-compiler-lib/Models/IdentifierReplacer.cs
> +    public static Regex CsharpIdRegex = new(@"{([A-Za-z0-9\.]+)\-id}", RegexOptions.Compiled);
Fixed

2022-01-19 15:10 UTC, fey101 commented on PowerShellBetaTests/SnippetExecutionBetaTests.cs
> +﻿// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
How is this file different from PowerShellBetaExecutionTests/SnippetExecutionBetaTests.cs above? Do they do the same thing since there are no compilation tests for powershell?

2022-01-19 15:29 UTC, fey101 reviewed
👏🏽 , well done

2022-01-20 09:58 UTC, georgend commented on PowerShellBetaTests/SnippetExecutionBetaTests.cs
> +﻿// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
You raise a fair point. The current difference is in:-
![image](https://user-images.githubusercontent.com/1641829/150316074-5214f834-a53f-4f33-a278-b4d3240a0a28.png)

We followed the current structure of the CodeBase. C# v1.0 and beta tests are similarly structured. 
Can we keep it like this for now?

2022-01-20 17:12 UTC, fey101 commented on PowerShellBetaTests/SnippetExecutionBetaTests.cs
> +﻿// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
Yes, we can for now.

2022-01-20 18:05 UTC, zengin requested changes

2022-01-20 18:05 UTC, zengin commented on azure-pipelines/powershell-beta-execution-tests-known-issues.yml
> +     ref: snippet-generation/62136
I think `main` now has the PowerShell snippets.

2022-01-20 18:05 UTC, zengin commented on azure-pipelines/powershell-beta-execution-tests.yml
> +     ref: snippet-generation/62136
```suggestion
     ref: main
```

2022-01-20 18:05 UTC, zengin commented on azure-pipelines/powershell-v1-execution-tests-known-issues.yml
> +     ref: snippet-generation/62136
```suggestion
     ref: main
```

2022-01-20 18:05 UTC, zengin commented on azure-pipelines/powershell-v1-execution-tests.yml
> +     ref: snippet-generation/62136
```suggestion
     ref: main
```

2022-01-24 15:38 UTC, georgend commented on PowerShellBetaExecutionKnownFailureTests/SnippetExecutionV1Tests.cs
> +            Version = Versions.V1,
Cleaned up.

2022-01-24 20:24 UTC, zengin approved these changes

2022-01-24 20:24 UTC, merged