Typescript tests
microsoftgraph/msgraph-sdk-raptor pull request #759
Opened 2022-01-12 16:49 UTC by rkodev

Updating typescript tests to execute on the azure pipeline.

The branch is not yet ready for review

2022-01-12 18:25 UTC, baywet requested changes

2022-01-12 18:25 UTC, baywet commented on TypeScriptBetaTests/SnippetCompileBetaTests.cs
> +            //if (!Directory.Exists(TestsSetup.Config.Value.TypeScriptFolder) || !File.Exists(Path.Combine(TypeScriptFolder, "package.json")) || !File.Exists(Path.Combine(TypeScriptFolder, "package-l
commented out code

2022-01-12 18:25 UTC, baywet commented on azure-pipelines/typescript-beta-compile-tests.yml
> +     endpoint: georgend
update the endpoint to the micrososftgraph one before merging

2022-01-12 18:25 UTC, baywet commented on azure-pipelines/typescript-beta-compile-tests.yml
> +        versionSpec: '6.x'
why such an old version? this probably negatively impacts performance

2022-01-12 18:25 UTC, baywet commented on msgraph-sdk-raptor-compiler-lib/MicrosoftGraphTypescriptCompiler.cs
> +                catch(Exception ex)
error swallowing, remove or log

2022-01-13 15:00 UTC, baywet requested changes

2022-01-13 15:00 UTC, baywet commented on TestsCommon/TypeScriptTestRunner.cs
> +            var fileName = $"{testData.Version.ToString().ToLower()}-{testData.FileName.ToLower().Replace(" ", "-")}.ts";
```suggestion
            var fileName = $"{testData.Version.ToString().ToLowerInvariant()}-{testData.FileName.ToLowerInvariant().Replace(" ", "-")}.ts";
```

2022-01-13 15:00 UTC, baywet commented on TestsCommon/TypeScriptTestRunner.cs
> +        {
defensive programing

2022-01-13 15:00 UTC, baywet commented on TestsCommon/TypeScriptTestRunner.cs
> +            File.WriteAllText(Path.Combine(TestsSetup.Config.Value.TypeScriptFolder, $"{testData.Version.ToString(CultureInfo.InvariantCulture).ToLower(CultureInfo.InvariantCulture)}-{testData.FileNa
```suggestion
            File.WriteAllText(Path.Combine(TestsSetup.Config.Value.TypeScriptFolder, $"{testData.Version.ToString().ToLowerInvariant()}-{testData.FileName.ToLowerInvariant().Replace(" ", "-")}.ts"), codeToCompile);
```

2022-01-13 15:00 UTC, baywet commented on azure-pipelines/typescript-templates/tsconfig.json
> +		"target": "ES2015",
should we use node/es6 modules and es2018 instead for our integration testing? (this should impact performance positively)

2022-01-14 19:15 UTC, zengin requested changes

2022-01-14 19:15 UTC, zengin commented on TestsCommon/TypeScriptTestRunner.cs
> +            var stdErr = stdErrSB.ToString();
Because we are not doing any stream processing, I think we can redirect the output into files.

how to assign stdout to stream: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.standardoutput?view=net-6.0#examples

how to write stream to a file: https://stackoverflow.com/a/9821313

2022-01-14 19:15 UTC, zengin commented on azure-pipelines/typescript-beta-compile-tests.yml
> +        filePath : $(Build.SourcesDirectory)/msgraph-sdk-raptor/azure-pipelines/typescript-templates/build-typescript.sh
please add `displayName` property to show what the step does in the pipeline.

2022-01-14 19:15 UTC, zengin commented on azure-pipelines/typescript-templates/build-typescript.sh
> +#!/bin/bash
nit: PowerShell is more widely known in the team and more modern than bash. Let me or @georgend know if we can help in translating into PowerShell.

This is not a super complicated bash script, so it is not a blocker, but a nice to have ;)

2022-01-17 09:49 UTC, rkodev commented on azure-pipelines/typescript-templates/tsconfig.json
> +		"target": "ES2015",
Tested both and the build was relatively the same time. I think we can leave it at es2018 for better compatibility

2022-01-19 12:45 UTC, rkodev commented on TestsCommon/TypeScriptTestRunner.cs
> +            var stdErr = stdErrSB.ToString();
Redirecting the output to a file will require the file to be read later again. The output of this function is the StandardOutput and StandardError tuple

2022-01-19 12:46 UTC, rkodev commented on azure-pipelines/typescript-beta-compile-tests.yml
> +        filePath : $(Build.SourcesDirectory)/msgraph-sdk-raptor/azure-pipelines/typescript-templates/build-typescript.sh
done

2022-01-19 15:34 UTC, rkodev commented on TestsCommon/TypeScriptTestRunner.cs
> +        {
Resolved

2022-01-19 20:05 UTC, nikithauc commented on TestsCommon/TypeScriptTestRunner.cs
> +        /// Parses the results of the tsc process. A dictionary is returned containing the file name as the string and all the constinuent erros
I suggest that we write the error categorization process in the summary.

2022-01-24 13:28 UTC, baywet commented on azure-pipelines/typescript-templates/tsconfig.json
> +		"target": "ES2015",
better compatibility with what? we own the execution runtime in this case.

2022-01-24 13:59 UTC, rkodev commented on azure-pipelines/typescript-templates/tsconfig.json
> +		"target": "ES2015",
update to es2018

2022-02-03 17:00 UTC, zengin commented on azure-pipelines/typescript-templates/prepare-typescript-folder.ps1
> +    ## test pipeline with hard coded env. To be deleted
nit: please remove, consider leaving a comment with TODO keyword to make searching for these easier. You may do this in your next PR in order not to kick off all the checks for a comment change :)

2022-02-03 17:03 UTC, zengin commented on msgraph-sdk-raptor.sln
>  		{7008F2BA-A803-493D-969B-90DC0A56CD98}.Release|Any CPU.Build.0 = Release|Any CPU
We should remove all references to old project TypeScriptBetaTests, 757FC453-510F-4DD2-90F9-D652B026803E.

2022-02-03 18:30 UTC, baywet requested changes

2022-02-03 18:30 UTC, baywet commented on azure-pipelines/typescript-templates/.npmrc
> +@microsoft:registry=https://npm.pkg.github.com/microsoft
```suggestion
@microsoft:registry=https://npm.pkg.github.com
```

2022-02-03 18:31 UTC, baywet approved these changes

2022-02-03 19:04 UTC, merged