Initial Delegated Permissions Infrastructure.
microsoftgraph/msgraph-sdk-raptor pull request #816
Opened 2022-02-04 01:34 UTC by georgend

Includes Some duplicated code.
Pending cleanup.

2022-02-04 02:12 UTC, zengin requested changes
I am aware that this is work in progress, left a couple of comments to address to make sure that we address. LGTM from the functionality point of view.

2022-02-04 02:12 UTC, zengin commented on TestsCommon/PowerShellTestRunner.cs
> +    private static async Task<Scope[]> GetScopes(string httpMethod, string Uri, LanguageTestData testData)
please move to a shared file instead of copying

2022-02-04 02:12 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/PermissionManager.cs
> +    public async Task<TokenCredential> GetTokenCredential(Scope delegatedPermissionScope)
we probably want to cache these TokenCredential objects at the beginning of test run instead of creating more than once for each scope.

2022-02-08 16:44 UTC, fey101 commented on azure-pipelines/powershell-templates/prod-v1-powershell-scheduled-execution-tests-weekly.yml
> +  - cron: "0 3 * * *"  # every Wednesday at 3AM UTC (off hours for Redmond, Nairobi and Montréal)
This crontab specifies daily runs instead of weekly as described in name tag.

2022-02-08 17:35 UTC, georgend commented on azure-pipelines/powershell-templates/prod-v1-powershell-scheduled-execution-tests-weekly.yml
> +  - cron: "0 3 * * *"  # every Wednesday at 3AM UTC (off hours for Redmond, Nairobi and Montréal)
Thanks, oversight on my part.

2022-02-08 18:27 UTC, zengin requested changes

2022-02-08 18:27 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/RaptorUtils.cs
> +    public static class RaptorUtils
"utils" is a candidate for a place where people will dump unrelated logic. Let's scope its name to what it does right now, which is handling permission scopes.

2022-02-08 18:27 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/RaptorUtils.cs
> +    public static class ResourceConstants
please move it to its own class.

2022-02-08 18:27 UTC, zengin commented on msgraph-sdk-raptor-compiler-lib/PermissionManager.cs
> +                var application = apps.First(c => c.Value == $"DelegatedApp {scopeName}");
FirstOrDefault followed by a null check. Because there might be cases where the application doesn't exist in the tenant.

2022-02-08 18:27 UTC, zengin commented on azure-pipelines/powershell-templates/prod-v1-powershell-scheduled-execution-tests-daily.yml
> +  - cron: "0 3 * * WED"  # every Wednesday at 3AM UTC (off hours for Redmond, Nairobi and Montréal)
cron doesn't match daily

2022-02-08 18:27 UTC, zengin commented on azure-pipelines/powershell-templates/prod-beta-powershell-scheduled-execution-tests-daily.yml
> +  - cron: "0 3 * * WED"  # every Wednesday at 3AM UTC (off hours for Redmond, Nairobi and Montréal)
cron doesn't match daily

2022-02-08 18:49 UTC, georgend commented on msgraph-sdk-raptor-compiler-lib/RaptorUtils.cs
> +    public static class RaptorUtils
This was a failure of imagination, I was worried about your exact sentiment when pushing this

2022-02-11 09:49 UTC, merged