Remove beta compilation fixed issues
microsoftgraph/msgraph-sdk-raptor pull request #822
Opened 2022-02-08 15:02 UTC by fey101

2022-02-08 17:23 UTC, zengin requested changes

2022-02-08 17:23 UTC, zengin commented on TestsCommon/CSharpKnownIssues.cs
> -                { $"event-tentativelyaccept-csharp-{version}-compiles", EventActionsShouldNotBeReorderedKnownIssue },
We need to understand how these issues are fixed. It shouldn't be passing until kiota based SDKs are released.

2022-02-09 14:27 UTC, fey101 commented on TestsCommon/CSharpKnownIssues.cs
> -                { $"event-tentativelyaccept-csharp-{version}-compiles", EventActionsShouldNotBeReorderedKnownIssue },
The kiota preview is not yet out as confirmed from Andrew so I've removed these testcases as the passing appears ephemeral just as you had suspected.

2022-02-10 16:29 UTC, zengin approved these changes

2022-02-10 16:29 UTC, merged