Includes known issues in TS compilation run
microsoftgraph/msgraph-sdk-raptor pull request #879
Opened 2022-03-07 09:14 UTC by rkodev

Includes known issues in TS compilation run

2022-03-08 00:00 UTC, zengin requested changes

2022-03-08 00:00 UTC, zengin commented on azure-pipelines/typescript-v1-compile-tests-combined.yml
> +      displayName: 'Replace test settings parameters'
I don't think you need this step, this is only needed if you are using a project that doesn't hard code a version (e.g. CSharpArbitraryDllTests). With default settings, `dotnet test TypeScriptV1KnownFailureTests` should pick the known issues.

2022-03-11 00:54 UTC, zengin commented on azure-pipelines/typescript-v1-compile-tests-combined.yml
> +        dotnet-version: 6.0.x
this is a GitHub Actions step, how does it work in Azure Pipelines? Consider using `common-templates/use-dotnet-sdk.yml` file instead.

2022-04-05 17:26 UTC, rkodev commented
@zengin Closing this Pr as it has been superseded with [the typescript refactor](https://github.com/microsoftgraph/msgraph-sdk-raptor/pull/931)

2022-04-05 17:26 UTC, closed without merging