Power shell identifiers replacement bug fix
microsoftgraph/msgraph-sdk-raptor pull request #905
Opened 2022-03-17 07:45 UTC by timayabi2020

Powershell snippets that have more than one placeholder that need to be replaced are failing.
In this scenario only one place holder will be replaced with the corresponding identifier in the identifiers.json file.
To correct this, a recursive call of the function that does those replacements has been implemented.

2022-03-17 22:01 UTC, zengin requested changes
please add a unit test with an example. I don't fully understand what the bug is and how this PR resolves the bug.

2022-03-18 08:09 UTC, timayabi2020 commented
> please add a unit test with an example. I don't fully understand what the bug is and how this PR resolves the bug.

Unit test has been added as per request

2022-03-29 13:30 UTC, georgend requested changes

2022-03-29 13:30 UTC, georgend commented on UnitTests/PowershellIdentifierReplacerTest.cs
> +    public void SinglePlaceHolderSnippetIdentifiedAsPowerShellShouldPass(string snippetWithSinglePlaceHolders, string expectedSnippetWithSinglePlaceHolders) => Assert.AreEqual(_idReplacer.ReplaceIds(
Using this method style affects readability:-
- line is too long across the screen. 
- Breaking it down into Arrange step, Act Step and Assert step, instead of a one liner would enhance readability and comprehension.

2022-03-29 13:38 UTC, georgend commented on TestsCommon/Models/IdentifierReplacer.cs
> +                if (language == Languages.PowerShell.ToString())
To avoid boxing, remove the `ToString` and change language to be of enum type `Languages`.

2022-03-29 13:39 UTC, georgend commented on TestsCommon/Models/IdentifierReplacer.cs
> +    private string ReplaceIdsFromIdentifiersFile(string input,string language)
Change `language` to be of type `Languages`

2022-03-29 13:49 UTC, georgend commented on TestsCommon/CSharpTestRunner.cs
> +        var (codeToCompile, codeSnippetFormatted) = GetCodeToCompile(IdentifierReplacer.Instance.ReplaceIds(fileContent,Languages.CSharp.ToString()));
Pass in Languages without turning to a string.

2022-03-29 13:50 UTC, georgend requested changes
Minor changes required

2022-03-29 15:11 UTC, timayabi2020 commented on TestsCommon/Models/IdentifierReplacer.cs
> +                if (language == Languages.PowerShell.ToString())
This is also done. The type has been changed from language to Languages

2022-03-29 15:11 UTC, timayabi2020 commented on TestsCommon/Models/IdentifierReplacer.cs
> +        if (language == Languages.PowerShell.ToString())
This is also done

2022-03-29 15:11 UTC, timayabi2020 commented on TestsCommon/Models/IdentifierReplacer.cs
> +    private string ReplaceIdsFromIdentifiersFile(string input,string language)
This is also done

2022-03-29 15:12 UTC, timayabi2020 commented on TestsCommon/Models/IdentifierReplacer.cs
> +        List<Match>matchList = matches.ToList();
Removed ToList and made use of Count

2022-03-29 15:12 UTC, timayabi2020 commented on TestsCommon/CSharpTestRunner.cs
> +        var (codeToCompile, codeSnippetFormatted) = GetCodeToCompile(IdentifierReplacer.Instance.ReplaceIds(fileContent,Languages.CSharp.ToString()));
Also done

2022-03-30 10:08 UTC, georgend commented on TestsCommon/Models/IdentifierReplacer.cs
> +    public IdentifierReplacer(IDTree tree,string language)
Switch to the language Enum here as well.

2022-03-30 10:09 UTC, georgend commented on TestsCommon/Models/IdentifierReplacer.cs
> +        _identifierRegex =  language==Languages.CSharp.ToString()?IdentifierRegexes.CsharpIdRegex:IdentifierRegexes.PowerShellIdRegex;
Switch to the language enum here as well eliminate the `ToString()`

2022-03-30 20:53 UTC, zengin commented
@timayabi2020 thanks for writing the unit tests.

There is no need to have a code change for multiple ID scenarios, because the same problem exists in C# implementation and we already resolved it by iterating on the tree and regex matches at the same time. We should not call the replaceId function recursively as the iteration already covers that scenario.

I was able to revert your code changes and added user->event into the identifiers.json file and the test case `SnippetWithMultiplePlaceHoldersShouldPass` still passes.

2022-03-31 04:35 UTC, timayabi2020 commented
> @timayabi2020 thanks for writing the unit tests.
> 
> There is no need to have a code change for multiple ID scenarios, because the same problem exists in C# implementation and we already resolved it by iterating on the tree and regex matches at the same time. We should not call the replaceId function recursively as the iteration already covers that scenario.
> 
> I was able to revert your code changes and added user->event into the identifiers.json file and the test case `SnippetWithMultiplePlaceHoldersShouldPass` still passes.

I had also explored that option locally but my question is, do we have the flexibility of doing such modifications on the identifiers.json file in cloud? There is a possibility that powershell snippets might  have more than two or three Id placeholders and I think it will be cumbersome to always manually add an object with its values under one primary object . e.g user->event->calender->etc->etc->etc.

2022-03-31 15:56 UTC, zengin commented
@timayabi2020 we have all the flexibility to change identifiers.json. The only thing that I'd suggest we watch out for is that the same hierarchy exists between C# and PowerShell. If that is not the case, we can reevaluate if we need a separate identifiers.json file for PowerShell tests. But given the high pass rate, I really doubt there is a huge difference between the two languages, if there is any.

2022-04-04 13:53 UTC, timayabi2020 commented
> > @timayabi2020 we have all the flexibility to change identifiers.json. The only thing that I'd suggest we watch out for is that the same hierarchy exists between C# and PowerShell. If that is not the case, we can reevaluate if we need a separate identifiers.json file for PowerShell tests. But given the high pass rate, I really doubt there is a huge difference between the two languages, if there is any.
> 
> @zengin Since we have the flexibility to update the identifiers.json file, I have made an update to this PR to only include unit tests for powershell identifier replacement and updates on powershell known issues file. The other changes on Identifier replacement function has been rolled back too.

2022-04-04 16:05 UTC, zengin approved these changes

2022-04-05 08:06 UTC, fey101 approved these changes

2022-04-05 17:37 UTC, georgend approved these changes

2022-04-07 07:46 UTC, merged