Onboard go on raptor
microsoftgraph/msgraph-sdk-raptor pull request #954
Opened 2022-04-09 21:14 UTC by fey101

- Separate sources directory and docsRepoCheckoutdirectory config settings. 
- write project to run goV1Tests.

2022-04-11 00:14 UTC, zengin requested changes
Great first draft! Left a few comments..

2022-04-11 00:14 UTC, zengin commented on GoV1Tests/goDependencies/build.txt
> +module RaptorGoTests
consider using go.mod file format, so that we can get dependabot updates for the dependencies.

2022-04-11 00:14 UTC, zengin commented on TestsCommon/GoTestRunner.cs
> +public class GoTestRunner
```suggestion
public static class GoTestRunner
```

2022-04-11 00:14 UTC, zengin commented on TestsCommon/GoTestRunner.cs
> +    /// matches csharp snippet from C# snippets markdown output
comment doesn't match.

2022-04-11 00:14 UTC, zengin commented on TestsCommon/GoTestRunner.cs
> +    /// compiled version of the C# markdown regular expression
comment doesn't match

2022-04-11 00:14 UTC, zengin commented on TestsCommon/GoTestRunner.cs
> +
please remove, this is C# specific.
```suggestion
```

2022-04-11 00:14 UTC, zengin commented on TestsCommon/GoTestRunner.cs
> +    public static string ReplaceHyphensWithUnderscores(string stringContent)
```suggestion
    private static string ReplaceHyphensWithUnderscores(string stringContent)
```

2022-04-11 00:14 UTC, zengin commented on TestsCommon/GoTestRunner.cs
> +    }
please remove, this is C# specific.
```suggestion
```

2022-04-11 00:14 UTC, zengin commented on TestsCommon/GraphDocsDirectory.cs
> +        var msGraphDocsRepoLocation = TestsSetup.Config.Value.DocsRepoCheckoutDirectory;
what is the reason for this change? We retired this config value a while ago, the decision was to use `BUILD_SOURCESDIRECTORY` for both local and cloud runs.

2022-04-19 14:40 UTC, fey101 commented
Closing this in favor of https://github.com/microsoftgraph/msgraph-sdk-raptor/pull/989. Somehow this remote branch is no longer connected to the local branch and I cannot trace this branch on running `git branch -a`. Also tried git push -u origin <this-branch-name> but got an error "fatal: Onboard-go-on-raptor cannot be resolved to branch"

2022-04-19 14:40 UTC, closed without merging