Fix/typescript known issues
microsoftgraph/msgraph-sdk-raptor pull request #968
Opened 2022-04-12 16:20 UTC by rkodev

This PR Updates Typescript known issues and failures.

https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_apis/build/builds/72326/logs/16

2022-04-12 16:27 UTC, zengin requested changes

2022-04-12 16:27 UTC, zengin commented on TestsCommon/TypeScriptTestRunner.cs
> +                    }
could you please check if you can reuse ProcessSpawner in this case?

2022-04-12 20:10 UTC, rkodev commented on TestsCommon/TypeScriptTestRunner.cs
> +                    }
done

2022-04-13 00:46 UTC, zengin approved these changes

2022-04-13 06:25 UTC, merged